module.exports = {
    httpUnsafeOrigin: 'https://docs.seanhealy.ie',
    httpSafeOrigin: "https://secure-docs.seanhealy.ie",
    httpAddress: '::',
    httpPort: 3000,
    httpSafePort: 3001,
    maxWorkers: 3,
    adminKeys: [
        "[sean@localhost:3000/dBtIEXMd49i4dKmKj3sNHxvIweVfVttfcpkHg8HDLOU=]"
    ],
	defaultStorageLimit: 1024 * 1024 * 1024 * 1024,
    inactiveTime: 3,
    archiveRetentionTime: 3,
    maxUploadSize: 4 * 1024 * 1024 * 1024,
    filePath: './datastore/',
    archivePath: './data/archive',
    pinPath: './data/pins',
    taskPath: './data/tasks',
    blockPath: './block',
    blobPath: './blob',
    blobStagingPath: './data/blobstage',
    decreePath: './data/decrees',
    logPath: './data/logs',
    logToStdout: true,
    logLevel: 'info',
    logFeedback: false,
    verbose: false,
    installMethod: 'unspecified',
};
