module.exports = {
	httpUnsafeOrigin: 'https://docs.seanhealy.ie',
	httpSafeOrigin: "https://secure-docs.seanhealy.ie",
	httpAddress: '::',
	httpPort: 3000,
	httpSafePort: 3001,
	maxWorkers: 3,
	adminKeys: [
	],
	defaultStorageLimit: 1024 * 1024 * 1024 * 1024,
	inactiveTime: 3,
	archiveRetentionTime: 3,
	maxUploadSize: 4 * 1024 * 1024 * 1024,
	filePath: '{{cryptpad_file_path}}',
	archivePath: '{{cryptpad_archive_path}}',
	pinPath: '{{cryptpad_pin_path}}',
	taskPath: '{{cryptpad_task_path}}',
	blockPath: '{{cryptpad_block_path}}',
	blobPath: '{{cryptpad_blob_path}}',
	blobStagingPath: '{{cryptpad_blob_staging_path}}',
	decreePath: '{{cryptpad_decree_path}}',
	logPath: '{{cryptpad_log_path}}',
	logToStdout: true,
	logLevel: 'info',
	logFeedback: false,
	verbose: false,
	installMethod: 'unspecified',
};
