module.exports = {
	httpUnsafeOrigin: 'https://docs.seanhealy.ie',
	httpSafeOrigin: "https://secure-docs.seanhealy.ie",
	httpAddress: '::',
	httpPort: 3000,
	httpSafePort: 3001,
	maxWorkers: 3,
	adminKeys: [
	],
	defaultStorageLimit: 1024 * 1024 * 1024 * 1024,
	inactiveTime: 3,
	archiveRetentionTime: 3,
	maxUploadSize: 4 * 1024 * 1024 * 1024,
	filePath: '{{file_path}}',
	archivePath: '{{archive_path}}',
	pinPath: '{{pin_path}}',
	taskPath: '{{task_path}}',
	blockPath: '{{block_path}}',
	blobPath: '{{blob_path}}',
	blobStagingPath: '{{blob_staging_path}}',
	decreePath: '{{decree_path}}',
	logPath: '{{log_path}}',
	logToStdout: true,
	logLevel: 'info',
	logFeedback: false,
	verbose: false,
	installMethod: 'unspecified',
};
